# Purpose: Materialize and prune immutable content-addressed public-plugin generations.
# Map: subsystems/nodes_registry_builtins.md
# Tests: tests/test_plugin_loader.py

from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
from collections.abc import Iterable, Mapping
from pathlib import Path, PurePosixPath, PureWindowsPath
from uuid import uuid4

MANIFEST_FILENAME = "node_package.json"
_SHA256_LENGTH = 64


def _is_reparse_point(path: Path) -> bool:
    try:
        file_status = os.lstat(path)
    except OSError:
        return False
    attributes = getattr(file_status, "st_file_attributes", 0)
    return stat.S_ISLNK(file_status.st_mode) or bool(
        attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    )


def _digest(value: object) -> str:
    text = str(value)
    if len(text) != _SHA256_LENGTH or any(
        character not in "0123456789abcdef" for character in text
    ):
        raise ValueError("generation digest must be a lowercase SHA-256 digest")
    return text


def _member_path(value: object) -> str:
    text = str(value)
    path = PurePosixPath(text)
    windows_path = PureWindowsPath(text)
    if (
        not text
        or "\\" in text
        or ":" in text
        or path.is_absolute()
        or windows_path.drive
        or windows_path.root
        or path.as_posix() != text
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise ValueError("generation members must use canonical relative paths")
    return text


def canonical_manifest_bytes(manifest: Mapping[str, object]) -> bytes:
    return json.dumps(
        dict(manifest),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def canonical_bundle_digest(
    manifest: Mapping[str, object],
    members: Mapping[str, bytes],
) -> str:
    normalized = {
        _member_path(path): bytes(payload) for path, payload in members.items()
    }
    digest = hashlib.sha256(canonical_manifest_bytes(manifest))
    for path in sorted(normalized):
        digest.update(path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(normalized[path])
    return digest.hexdigest()


def _expected_generation_members(
    manifest: Mapping[str, object],
    members: Mapping[str, bytes],
) -> dict[str, bytes]:
    expected = {
        _member_path(path): bytes(payload) for path, payload in members.items()
    }
    if MANIFEST_FILENAME in expected:
        raise ValueError(f"{MANIFEST_FILENAME} is generated by COREX")
    expected[MANIFEST_FILENAME] = canonical_manifest_bytes(manifest)
    return expected


def _generation_matches(directory: Path, expected: Mapping[str, bytes]) -> bool:
    if _is_reparse_point(directory):
        return False
    actual_paths: set[str] = set()
    path_limit = max(16, len(expected) * 4)
    for index, path in enumerate(directory.rglob("*")):
        if index >= path_limit or _is_reparse_point(path):
            return False
        if path.is_file():
            try:
                if path.stat().st_nlink != 1:
                    return False
            except OSError:
                return False
            actual_paths.add(path.relative_to(directory).as_posix())
    if actual_paths != set(expected):
        return False
    for relative_path, payload in expected.items():
        path = directory / relative_path
        try:
            if path.stat().st_size != len(payload):
                return False
            with path.open("rb") as stream:
                if stream.read(len(payload) + 1) != payload:
                    return False
        except OSError:
            return False
    return True


def materialize_plugin_generation(
    generation_root: Path,
    *,
    bundle_digest: str,
    manifest: Mapping[str, object],
    members: Mapping[str, bytes],
) -> Path:
    digest = _digest(bundle_digest)
    expected = _expected_generation_members(manifest, members)
    configured_root = Path(generation_root)
    if _is_reparse_point(configured_root):
        raise ValueError("plugin generation root must not be a symlink")
    root = configured_root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    destination = root / digest
    if destination.exists():
        if (
            _is_reparse_point(destination)
            or not destination.is_dir()
            or not _generation_matches(destination, expected)
        ):
            raise ValueError("Existing plugin generation does not match its digest")
        return destination

    staging = root / f".{digest}.{uuid4().hex}.staging"
    staging.mkdir(parents=False, exist_ok=False)
    try:
        for relative_path, payload in expected.items():
            target = staging / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
        if not _generation_matches(staging, expected):
            raise ValueError("Staged plugin generation verification failed")
        try:
            staging.replace(destination)
        except OSError:
            if not destination.is_dir() or not _generation_matches(destination, expected):
                raise
            shutil.rmtree(staging)
    except Exception:
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
        raise
    return destination


def prune_plugin_generations(
    generation_root: Path,
    *,
    active_digests: Iterable[str],
    referenced_digests: Iterable[str],
) -> tuple[str, ...]:
    configured_root = Path(generation_root)
    if _is_reparse_point(configured_root):
        raise ValueError("plugin generation root must not be a symlink")
    root = configured_root.resolve()
    if not root.is_dir():
        return ()
    protected = {
        *(_digest(value) for value in active_digests),
        *(_digest(value) for value in referenced_digests),
    }
    removed: list[str] = []
    for child in sorted(root.iterdir(), key=lambda path: path.name):
        try:
            digest = _digest(child.name)
        except ValueError:
            continue
        if digest in protected or _is_reparse_point(child) or not child.is_dir():
            continue
        try:
            shutil.rmtree(child)
        except OSError:
            continue
        else:
            removed.append(digest)
    return tuple(removed)


__all__ = [
    "MANIFEST_FILENAME",
    "canonical_bundle_digest",
    "canonical_manifest_bytes",
    "materialize_plugin_generation",
    "prune_plugin_generations",
]
