flowchart LR
    U[User] --> MS[MainShell.qml]
    MS --> GC[GraphCanvas.qml orchestrator]
    MS --> SW[ShellWindow facade]

    GC --> GCBG[GraphCanvasBackground]
    GC --> GCDP[GraphCanvasDropPreview]
    GC --> GCMINI[GraphCanvasMinimapOverlay]
    GC --> GCINPUT[GraphCanvasInputLayers]
    GC --> GCCM[GraphCanvasContextMenus]
    GC --> GCLOGIC[GraphCanvasLogic.js]
    GC --> EDGE[EdgeLayer]
    GC --> NODECARD[NodeCard]

    GC --> GS
    GC --> VP
    GC --> SW

    SW --> RUN[RunController]
    SW --> PSC[ProjectSessionController]
    SW --> WLC[WorkspaceLibraryController]
    SW --> SEARCH[window_search_scope_state]

    SW --> GS[GraphSceneBridge]
    SW --> VP[ViewportBridge]
    SW --> MODELS[ConsoleModel + StatusItemModel + ScriptEditorModel + WorkspaceTabsModel]

    GS --> GR[(GraphModel)]
    GS --> HIER[graph.hierarchy]
    GS --> XFORM[graph.transforms]
    GS --> HIST[(RuntimeGraphHistory)]

    WLC --> NAV[WorkspaceViewNavOps]
    WLC --> EDIT[WorkspaceEditOps]
    WLC --> DROP[WorkspaceDropConnectOps]
    WLC --> IO[WorkspaceIOOps]
    WLC --> GI[GraphInteractions]

    EDIT --> GS
    GI --> GS
    NAV --> WM[WorkspaceManager]
    WM --> GR

    WLC --> CWF[custom_workflows codec]

    RUN --> SER[JsonProjectSerializer]
    PSC --> SER
    PSC --> SESS[SessionAutosaveStore]

    SER --> MIG[JsonProjectMigration]
    SER --> CODEC[JsonProjectCodec]
    SER --> SFE[(.sfe project files)]
    SESS --> LAST[(last_session.json)]
    SESS --> AUTO[(autosave.sfe)]

    SW --> REG[NodeRegistry]
    REG --> BUILTINS[nodes.builtins.*]
    REG --> PLUG[plugin_loader]
    PLUG --> PLUGDIR[(APPDATA/EA_Node_Editor/plugins)]
    PLUG --> ENTRYPTS[(Python entry points)]

    RUN --> EXEC[ProcessExecutionClient]
    EXEC -->|commands| CMDQ[(command_queue)]
    CMDQ --> WORKER[worker_main / run_workflow]
    WORKER -->|events| EVTQ[(event_queue)]
    EVTQ --> EXEC
    WORKER --> REG
    WORKER --> NODEPLUGINS[NodePlugin.execute / async_execute]

    SW --> METRICS[telemetry.system_metrics]
